// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: QueryServer.proto

package GrpcServer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	durationpb "google.golang.org/protobuf/types/known/durationpb"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QueryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sql           string                 `protobuf:"bytes,1,opt,name=sql,proto3" json:"sql,omitempty"`
	Params        []string               `protobuf:"bytes,2,rep,name=params,proto3" json:"params,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_QueryServer_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{0}
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParams() []string {
	if x != nil {
		return x.Params
	}
	return nil
}

type Interval struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Months        int32                  `protobuf:"varint,1,opt,name=months,proto3" json:"months,omitempty"`
	Days          int32                  `protobuf:"varint,2,opt,name=days,proto3" json:"days,omitempty"`
	Micros        int64                  `protobuf:"varint,3,opt,name=micros,proto3" json:"micros,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Interval) Reset() {
	*x = Interval{}
	mi := &file_QueryServer_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Interval) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Interval) ProtoMessage() {}

func (x *Interval) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Interval.ProtoReflect.Descriptor instead.
func (*Interval) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{1}
}

func (x *Interval) GetMonths() int32 {
	if x != nil {
		return x.Months
	}
	return 0
}

func (x *Interval) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

func (x *Interval) GetMicros() int64 {
	if x != nil {
		return x.Micros
	}
	return 0
}

type MapValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        map[string]*Value      `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MapValue) Reset() {
	*x = MapValue{}
	mi := &file_QueryServer_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MapValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MapValue) ProtoMessage() {}

func (x *MapValue) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MapValue.ProtoReflect.Descriptor instead.
func (*MapValue) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{2}
}

func (x *MapValue) GetFields() map[string]*Value {
	if x != nil {
		return x.Fields
	}
	return nil
}

type ListValue struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListValue) Reset() {
	*x = ListValue{}
	mi := &file_QueryServer_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListValue) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListValue) ProtoMessage() {}

func (x *ListValue) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListValue.ProtoReflect.Descriptor instead.
func (*ListValue) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{3}
}

func (x *ListValue) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

// Value represents a single value of any supported type.
type Value struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Kind:
	//
	//	*Value_NullValue
	//	*Value_DoubleValue
	//	*Value_Int64Value
	//	*Value_BoolValue
	//	*Value_StringValue
	//	*Value_BytesValue
	//	*Value_TimestampValue
	//	*Value_DurationValue
	//	*Value_IntervalValue
	//	*Value_ListValue
	//	*Value_MapValue
	Kind          isValue_Kind `protobuf_oneof:"kind"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Value) Reset() {
	*x = Value{}
	mi := &file_QueryServer_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Value) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Value) ProtoMessage() {}

func (x *Value) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Value.ProtoReflect.Descriptor instead.
func (*Value) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{4}
}

func (x *Value) GetKind() isValue_Kind {
	if x != nil {
		return x.Kind
	}
	return nil
}

func (x *Value) GetNullValue() structpb.NullValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_NullValue); ok {
			return x.NullValue
		}
	}
	return structpb.NullValue(0)
}

func (x *Value) GetDoubleValue() float64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_DoubleValue); ok {
			return x.DoubleValue
		}
	}
	return 0
}

func (x *Value) GetInt64Value() int64 {
	if x != nil {
		if x, ok := x.Kind.(*Value_Int64Value); ok {
			return x.Int64Value
		}
	}
	return 0
}

func (x *Value) GetBoolValue() bool {
	if x != nil {
		if x, ok := x.Kind.(*Value_BoolValue); ok {
			return x.BoolValue
		}
	}
	return false
}

func (x *Value) GetStringValue() string {
	if x != nil {
		if x, ok := x.Kind.(*Value_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Value) GetBytesValue() []byte {
	if x != nil {
		if x, ok := x.Kind.(*Value_BytesValue); ok {
			return x.BytesValue
		}
	}
	return nil
}

func (x *Value) GetTimestampValue() *timestamppb.Timestamp {
	if x != nil {
		if x, ok := x.Kind.(*Value_TimestampValue); ok {
			return x.TimestampValue
		}
	}
	return nil
}

func (x *Value) GetDurationValue() *durationpb.Duration {
	if x != nil {
		if x, ok := x.Kind.(*Value_DurationValue); ok {
			return x.DurationValue
		}
	}
	return nil
}

func (x *Value) GetIntervalValue() *Interval {
	if x != nil {
		if x, ok := x.Kind.(*Value_IntervalValue); ok {
			return x.IntervalValue
		}
	}
	return nil
}

func (x *Value) GetListValue() *ListValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_ListValue); ok {
			return x.ListValue
		}
	}
	return nil
}

func (x *Value) GetMapValue() *MapValue {
	if x != nil {
		if x, ok := x.Kind.(*Value_MapValue); ok {
			return x.MapValue
		}
	}
	return nil
}

type isValue_Kind interface {
	isValue_Kind()
}

type Value_NullValue struct {
	NullValue structpb.NullValue `protobuf:"varint,1,opt,name=null_value,json=nullValue,proto3,enum=google.protobuf.NullValue,oneof"`
}

type Value_DoubleValue struct {
	DoubleValue float64 `protobuf:"fixed64,2,opt,name=double_value,json=doubleValue,proto3,oneof"`
}

type Value_Int64Value struct {
	Int64Value int64 `protobuf:"varint,3,opt,name=int64_value,json=int64Value,proto3,oneof"`
}

type Value_BoolValue struct {
	BoolValue bool `protobuf:"varint,4,opt,name=bool_value,json=boolValue,proto3,oneof"`
}

type Value_StringValue struct {
	StringValue string `protobuf:"bytes,5,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Value_BytesValue struct {
	BytesValue []byte `protobuf:"bytes,6,opt,name=bytes_value,json=bytesValue,proto3,oneof"`
}

type Value_TimestampValue struct {
	TimestampValue *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=timestamp_value,json=timestampValue,proto3,oneof"`
}

type Value_DurationValue struct {
	DurationValue *durationpb.Duration `protobuf:"bytes,8,opt,name=duration_value,json=durationValue,proto3,oneof"`
}

type Value_IntervalValue struct {
	IntervalValue *Interval `protobuf:"bytes,9,opt,name=interval_value,json=intervalValue,proto3,oneof"`
}

type Value_ListValue struct {
	ListValue *ListValue `protobuf:"bytes,10,opt,name=list_value,json=listValue,proto3,oneof"`
}

type Value_MapValue struct {
	MapValue *MapValue `protobuf:"bytes,11,opt,name=map_value,json=mapValue,proto3,oneof"`
}

func (*Value_NullValue) isValue_Kind() {}

func (*Value_DoubleValue) isValue_Kind() {}

func (*Value_Int64Value) isValue_Kind() {}

func (*Value_BoolValue) isValue_Kind() {}

func (*Value_StringValue) isValue_Kind() {}

func (*Value_BytesValue) isValue_Kind() {}

func (*Value_TimestampValue) isValue_Kind() {}

func (*Value_DurationValue) isValue_Kind() {}

func (*Value_IntervalValue) isValue_Kind() {}

func (*Value_ListValue) isValue_Kind() {}

func (*Value_MapValue) isValue_Kind() {}

// Row represents a single row of data.
// The order of values corresponds to the order of column_names in the Header.
type Row struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Values        []*Value               `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Row) Reset() {
	*x = Row{}
	mi := &file_QueryServer_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Row) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Row) ProtoMessage() {}

func (x *Row) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Row.ProtoReflect.Descriptor instead.
func (*Row) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{5}
}

func (x *Row) GetValues() []*Value {
	if x != nil {
		return x.Values
	}
	return nil
}

type Column struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type          string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Column) Reset() {
	*x = Column{}
	mi := &file_QueryServer_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Column) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Column) ProtoMessage() {}

func (x *Column) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Column.ProtoReflect.Descriptor instead.
func (*Column) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{6}
}

func (x *Column) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Column) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

// Header describes the columns of the result set.
// It is sent as the first message in the stream.
type Header struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Columns       []*Column              `protobuf:"bytes,1,rep,name=columns,proto3" json:"columns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Header) Reset() {
	*x = Header{}
	mi := &file_QueryServer_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Header) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Header) ProtoMessage() {}

func (x *Header) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Header.ProtoReflect.Descriptor instead.
func (*Header) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{7}
}

func (x *Header) GetColumns() []*Column {
	if x != nil {
		return x.Columns
	}
	return nil
}

// ExecuteQueryResponse is a wrapper message for the stream.
// It can contain either a Header (the first message) or a Row.
type ExecuteQueryResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*ExecuteQueryResponse_Header
	//	*ExecuteQueryResponse_Row
	Result        isExecuteQueryResponse_Result `protobuf_oneof:"result"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteQueryResponse) Reset() {
	*x = ExecuteQueryResponse{}
	mi := &file_QueryServer_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteQueryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteQueryResponse) ProtoMessage() {}

func (x *ExecuteQueryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_QueryServer_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteQueryResponse.ProtoReflect.Descriptor instead.
func (*ExecuteQueryResponse) Descriptor() ([]byte, []int) {
	return file_QueryServer_proto_rawDescGZIP(), []int{8}
}

func (x *ExecuteQueryResponse) GetResult() isExecuteQueryResponse_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *ExecuteQueryResponse) GetHeader() *Header {
	if x != nil {
		if x, ok := x.Result.(*ExecuteQueryResponse_Header); ok {
			return x.Header
		}
	}
	return nil
}

func (x *ExecuteQueryResponse) GetRow() *Row {
	if x != nil {
		if x, ok := x.Result.(*ExecuteQueryResponse_Row); ok {
			return x.Row
		}
	}
	return nil
}

type isExecuteQueryResponse_Result interface {
	isExecuteQueryResponse_Result()
}

type ExecuteQueryResponse_Header struct {
	Header *Header `protobuf:"bytes,1,opt,name=header,proto3,oneof"`
}

type ExecuteQueryResponse_Row struct {
	Row *Row `protobuf:"bytes,2,opt,name=row,proto3,oneof"`
}

func (*ExecuteQueryResponse_Header) isExecuteQueryResponse_Result() {}

func (*ExecuteQueryResponse_Row) isExecuteQueryResponse_Result() {}

var File_QueryServer_proto protoreflect.FileDescriptor

const file_QueryServer_proto_rawDesc = "" +
	"\n" +
	"\x11QueryServer.proto\x12\vQueryServer\x1a\x1cgoogle/protobuf/struct.proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1egoogle/protobuf/duration.proto\"8\n" +
	"\fQueryRequest\x12\x10\n" +
	"\x03sql\x18\x01 \x01(\tR\x03sql\x12\x16\n" +
	"\x06params\x18\x02 \x03(\tR\x06params\"N\n" +
	"\bInterval\x12\x16\n" +
	"\x06months\x18\x01 \x01(\x05R\x06months\x12\x12\n" +
	"\x04days\x18\x02 \x01(\x05R\x04days\x12\x16\n" +
	"\x06micros\x18\x03 \x01(\x03R\x06micros\"\x94\x01\n" +
	"\bMapValue\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.QueryServer.MapValue.FieldsEntryR\x06fields\x1aM\n" +
	"\vFieldsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12(\n" +
	"\x05value\x18\x02 \x01(\v2\x12.QueryServer.ValueR\x05value:\x028\x01\"7\n" +
	"\tListValue\x12*\n" +
	"\x06values\x18\x01 \x03(\v2\x12.QueryServer.ValueR\x06values\"\xb7\x04\n" +
	"\x05Value\x12;\n" +
	"\n" +
	"null_value\x18\x01 \x01(\x0e2\x1a.google.protobuf.NullValueH\x00R\tnullValue\x12#\n" +
	"\fdouble_value\x18\x02 \x01(\x01H\x00R\vdoubleValue\x12!\n" +
	"\vint64_value\x18\x03 \x01(\x03H\x00R\n" +
	"int64Value\x12\x1f\n" +
	"\n" +
	"bool_value\x18\x04 \x01(\bH\x00R\tboolValue\x12#\n" +
	"\fstring_value\x18\x05 \x01(\tH\x00R\vstringValue\x12!\n" +
	"\vbytes_value\x18\x06 \x01(\fH\x00R\n" +
	"bytesValue\x12E\n" +
	"\x0ftimestamp_value\x18\a \x01(\v2\x1a.google.protobuf.TimestampH\x00R\x0etimestampValue\x12B\n" +
	"\x0eduration_value\x18\b \x01(\v2\x19.google.protobuf.DurationH\x00R\rdurationValue\x12>\n" +
	"\x0einterval_value\x18\t \x01(\v2\x15.QueryServer.IntervalH\x00R\rintervalValue\x127\n" +
	"\n" +
	"list_value\x18\n" +
	" \x01(\v2\x16.QueryServer.ListValueH\x00R\tlistValue\x124\n" +
	"\tmap_value\x18\v \x01(\v2\x15.QueryServer.MapValueH\x00R\bmapValueB\x06\n" +
	"\x04kind\"1\n" +
	"\x03Row\x12*\n" +
	"\x06values\x18\x01 \x03(\v2\x12.QueryServer.ValueR\x06values\"0\n" +
	"\x06Column\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\"7\n" +
	"\x06Header\x12-\n" +
	"\acolumns\x18\x01 \x03(\v2\x13.QueryServer.ColumnR\acolumns\"u\n" +
	"\x14ExecuteQueryResponse\x12-\n" +
	"\x06header\x18\x01 \x01(\v2\x13.QueryServer.HeaderH\x00R\x06header\x12$\n" +
	"\x03row\x18\x02 \x01(\v2\x10.QueryServer.RowH\x00R\x03rowB\b\n" +
	"\x06result2\\\n" +
	"\n" +
	"SQLService\x12N\n" +
	"\fExecuteQuery\x12\x19.QueryServer.QueryRequest\x1a!.QueryServer.ExecuteQueryResponse0\x01B\x11Z\x0fgrpc/GrpcServerb\x06proto3"

var (
	file_QueryServer_proto_rawDescOnce sync.Once
	file_QueryServer_proto_rawDescData []byte
)

func file_QueryServer_proto_rawDescGZIP() []byte {
	file_QueryServer_proto_rawDescOnce.Do(func() {
		file_QueryServer_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_QueryServer_proto_rawDesc), len(file_QueryServer_proto_rawDesc)))
	})
	return file_QueryServer_proto_rawDescData
}

var file_QueryServer_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_QueryServer_proto_goTypes = []any{
	(*QueryRequest)(nil),          // 0: QueryServer.QueryRequest
	(*Interval)(nil),              // 1: QueryServer.Interval
	(*MapValue)(nil),              // 2: QueryServer.MapValue
	(*ListValue)(nil),             // 3: QueryServer.ListValue
	(*Value)(nil),                 // 4: QueryServer.Value
	(*Row)(nil),                   // 5: QueryServer.Row
	(*Column)(nil),                // 6: QueryServer.Column
	(*Header)(nil),                // 7: QueryServer.Header
	(*ExecuteQueryResponse)(nil),  // 8: QueryServer.ExecuteQueryResponse
	nil,                           // 9: QueryServer.MapValue.FieldsEntry
	(structpb.NullValue)(0),       // 10: google.protobuf.NullValue
	(*timestamppb.Timestamp)(nil), // 11: google.protobuf.Timestamp
	(*durationpb.Duration)(nil),   // 12: google.protobuf.Duration
}
var file_QueryServer_proto_depIdxs = []int32{
	9,  // 0: QueryServer.MapValue.fields:type_name -> QueryServer.MapValue.FieldsEntry
	4,  // 1: QueryServer.ListValue.values:type_name -> QueryServer.Value
	10, // 2: QueryServer.Value.null_value:type_name -> google.protobuf.NullValue
	11, // 3: QueryServer.Value.timestamp_value:type_name -> google.protobuf.Timestamp
	12, // 4: QueryServer.Value.duration_value:type_name -> google.protobuf.Duration
	1,  // 5: QueryServer.Value.interval_value:type_name -> QueryServer.Interval
	3,  // 6: QueryServer.Value.list_value:type_name -> QueryServer.ListValue
	2,  // 7: QueryServer.Value.map_value:type_name -> QueryServer.MapValue
	4,  // 8: QueryServer.Row.values:type_name -> QueryServer.Value
	6,  // 9: QueryServer.Header.columns:type_name -> QueryServer.Column
	7,  // 10: QueryServer.ExecuteQueryResponse.header:type_name -> QueryServer.Header
	5,  // 11: QueryServer.ExecuteQueryResponse.row:type_name -> QueryServer.Row
	4,  // 12: QueryServer.MapValue.FieldsEntry.value:type_name -> QueryServer.Value
	0,  // 13: QueryServer.SQLService.ExecuteQuery:input_type -> QueryServer.QueryRequest
	8,  // 14: QueryServer.SQLService.ExecuteQuery:output_type -> QueryServer.ExecuteQueryResponse
	14, // [14:15] is the sub-list for method output_type
	13, // [13:14] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_QueryServer_proto_init() }
func file_QueryServer_proto_init() {
	if File_QueryServer_proto != nil {
		return
	}
	file_QueryServer_proto_msgTypes[4].OneofWrappers = []any{
		(*Value_NullValue)(nil),
		(*Value_DoubleValue)(nil),
		(*Value_Int64Value)(nil),
		(*Value_BoolValue)(nil),
		(*Value_StringValue)(nil),
		(*Value_BytesValue)(nil),
		(*Value_TimestampValue)(nil),
		(*Value_DurationValue)(nil),
		(*Value_IntervalValue)(nil),
		(*Value_ListValue)(nil),
		(*Value_MapValue)(nil),
	}
	file_QueryServer_proto_msgTypes[8].OneofWrappers = []any{
		(*ExecuteQueryResponse_Header)(nil),
		(*ExecuteQueryResponse_Row)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_QueryServer_proto_rawDesc), len(file_QueryServer_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_QueryServer_proto_goTypes,
		DependencyIndexes: file_QueryServer_proto_depIdxs,
		MessageInfos:      file_QueryServer_proto_msgTypes,
	}.Build()
	File_QueryServer_proto = out.File
	file_QueryServer_proto_goTypes = nil
	file_QueryServer_proto_depIdxs = nil
}
